- hosts: localhost
  roles:
    - system
  tasks:
    # editors, IDEs, terminals, etc
    - include: tasks/visual-studio-code.yml

    # tools
    - include: tasks/docker.yml

    # languages
    - include: tasks/node.yml
    - include: tasks/ruby.yml
    - include: tasks/erlang.yml
    - include: tasks/elixir.yml
    - include: tasks/haskell.yml

    # browsers
    - include: tasks/chrome.yml

    # media
    - include: tasks/spotify.yml

    # applications
    - include: tasks/pdf-reader.yml
