- name: Install core packages
  become: yes
  pacman:
    name:
      - git
      - curl
      - wget
      - tree
      - htop
      - zip
      - unzip

- name: Install image tools
  yay: name={{ item }}
  loop:
      - exiv2
      - perl-image-exiftool
      - libvips
