- name: Install core packages
  become: yes
  pacman:
    name:
      - curl
      - git
      - htop
      - vim
      - wget
      - tree
      - pacman-contrib

- name: Install Image tools
  yay: name={{ item }}
  loop:
      - exiv2
      - perl-image-exiftool
      - libvips 

