- include: pacman.yml
- include: core.yml
- include: shell.yml
- include: keyboard.yml
- include: audio.yml
- include: bluetooth.yml
- include: audio-player.yml
- include: video-player.yml
- include: image-viewer.yml
- include: pdf-reader.yml
- include: vim.yml
- include: fonts.yml
- include: file-manager.yml
- include: app-launcher.yml
- include: playerctl.yml
- include: window-manager.yml
- include: dotfiles.yml
